Repository iotaledger/bee, pull requests merged in 2020-06, with the labels that each got.

#79 Add build and test workflows
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: c-feature, e-low, p-critical, wg-infra

#81 Update CODEOWNERS file
  .github/CODEOWNERS
Labels: c-cleanup, e-low, p-critical, wg-infra

#83 Update actions/cache to v2
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: c-bug, e-medium, p-critical, wg-infra

#84 Add coverage workflow
  .github/workflows/coverage.yml
Labels: c-feature, e-medium, p-high, wg-infra

#82 Added `bee-ternary`
  Cargo.toml
  bee-main/Cargo.toml
  bee-ternary/Cargo.toml
  bee-ternary/LICENSE
  bee-ternary/README.md
  bee-ternary/src/lib.rs
  bee-ternary/src/raw.rs
  bee-ternary/src/serde.rs
  bee-ternary/src/t1b1.rs
  bee-ternary/src/t2b1.rs
  bee-ternary/src/t3b1.rs
  bee-ternary/src/t4b1.rs
  bee-ternary/src/t5b1.rs
  bee-ternary/src/trit/balanced.rs
  bee-ternary/src/trit/mod.rs
  bee-ternary/src/trit/unbalanced.rs
  bee-ternary/src/tryte.rs
  bee-ternary/tests/buf.rs
  bee-ternary/tests/common.rs
  bee-ternary/tests/serde.rs
  bee-ternary/tests/slice.rs
  bee-ternary/tests/trit.rs
  bee-ternary/tests/tryte.rs
Labels: c-feature, e-high, p-high, wg-ternary

#88 Add bee-ternary changelog for 0.1.0-alpha
  bee-ternary/CHANGELOG.md
Labels: c-documentation, e-low, p-high, wg-ternary

#87 fix(LICENSE): remove appendix from license files
  LICENSE
  bee-ternary/LICENSE
Labels: c-cleanup, e-low, p-high, wg-infra

#85 Add workflow badges on README
  README.md
Labels: c-documentation, e-low, p-low, wg-infra

#86 Edit contact security PGP key
  .github/SECURITY.md
Labels: c-security, e-low, p-medium, wg-infra

#90 fixed spacing in README header
  README.md
Labels: c-cleanup, e-low, p-low, wg-infra

#92 Update pull_request_template.md
  .github/pull_request_template.md
Labels: c-cleanup, e-low, p-low, wg-infra
